<html dir="ltr" lang="en-US">
    <head>
        <import src="views/partials/base/meta.phtml"/>
        <import src="views/partials/base/css.phtml"/>
        <title>${app.core.website.title}</title>
        <script src="/uiConstants.js"></script>
        <import src="views/partials/base/libs.phtml"/>
        <import src="views/partials/base/js.phtml"/>
        <import src="views/partials/base/service-worker.phtml"/>
    </head>
    <body>
        Blog Admin
    </body>
</html>