<!-- | MAIN STYLESHEET | -->
<css src="//assets/css/styles.scss"/>
<!--
    | Font Family CSS style for MONTSERRAT fonts
    | ******************************************
    | font-family: 'Montserrat Subrayada', sans-serif;
    | font-family: 'Montserrat Alternates', sans-serif;
    | font-family: 'Montserrat', sans-serif;
-->
<css src="${HTTP}://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,400,800|Montserrat+Subrayada:400,700|Montserrat:100,200,400,800"/>

<!--
    | Font Family CSS style for SOURCE SANS PRO

    | font-family: 'Source Sans Pro", sans-serif;
-->
<css src="${HTTP}://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700|Roboto:300,400,500,700"/>

<!--
    | Font Family CSS style for OVERPASS

    | font-family: 'Overpass Mono', monospace;
-->
<css src="${HTTP}://fonts.googleapis.com/css?family=Overpass+Mono:300,400,700"/>

<!--
    | Font Family CSS style for LIBRE BARCODE 128 TEXT (BARCODE)

    | font-family: 'Libre Barcode 128 Text', cursive;
-->
<css src="${HTTP}://fonts.googleapis.com/css?family=Libre+Barcode+128+Text"/>
